version: '2.1'
services:

    php-fpm:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    sogo:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    dovecot:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    postfix:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    acme:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    watchdog:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    api:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    mysql:
      image: alpine:3.18
      command: /bin/true
      restart: "no"
